/**
 * @author Billal Ghadie
 * @purpose          - A derivative of the Request class, the FloorRequest class 
 *                     stores all the information needed by the scheduler to handle
 *                     events generated by floors. 
 * @param direction  - The direction the calling customer would like to travel. 'u' for
 *       			   for and 'd' for down.
 */

public class ElevatorRequest{
	private int destFloor;
	private int carFloorNum;
	private boolean arrived;
	private boolean acceptingElevatorRequests;
	private boolean bufferFull;


	public ElevatorRequest() {
		this.acceptingElevatorRequests = true;
		this.bufferFull = false;
		this.arrived = false;
	}
	
	
	public synchronized void notifyElevatorRequest(int d) {
		while(!this.acceptingElevatorRequests) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}
		
		this.destFloor = d;
		
		this.acceptingElevatorRequests = false;
		
 		
		notifyAll();
		
	}
	
	public synchronized void updatedPosition(int pos) {
		while(!this.bufferFull) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}
		
		this.carFloorNum = pos;
		
		if (pos == this.destFloor) {
			arrived = true;
		}
	}
	
	public synchronized void requestServed() {
		while(!this.bufferFull) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}

		this.acceptingElevatorRequests = true;
		
		this.bufferFull = false;	
		
		notifyAll();
	}
	

		
	public int getDestFloor() { return this.destFloor; }
	
	public int getCarFloor() { return this.carFloorNum; }
	
	public boolean hasRequest() {return this.bufferFull;}
	
	public boolean hasArrived() {return this.arrived;}
	
	public String toString() {
		return "Making elevator request to: " + this.destFloor;
	}
	
}
