/**
 * @author Billal Ghadie
 * @purpose          - A derivative of the Request class, the FloorRequest class 
 *                     stores all the information needed by the scheduler to handle
 *                     events generated by floors. 
 * @param direction  - The direction the calling customer would like to travel. 'u' for
 *       			   for and 'd' for down.
 */

public class ElevatorRequest{
	private int destFloor;
	private int floorNum;
	private boolean arrived;
	private boolean acceptingElevatorRequests;
	private boolean bufferFull;


	public ElevatorRequest() {
		this.acceptingElevatorRequests = true;
		this.bufferFull = false;
		this.arrived = false;
	}
	
	
	public synchronized void notifyElevatorRequest(int f, int d) {
		while(!this.acceptingElevatorRequests) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}
		
		this.floorNum = f;
		
		this.destFloor = d;
		
		this.acceptingElevatorRequests = false;
		
		this.bufferFull = true;
		
		this.arrived = false;
		
		notifyAll();
		
	}
	
	public synchronized void updatedPosition(int pos, boolean receivedPassengers) {
		while(!this.bufferFull) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}
		
		System.out.println("Current Pos of Elevator: "+ pos);
		
		if(receivedPassengers && pos == this.destFloor) {
			this.arrived = true;
			this.bufferFull = false;
		}
		
		notifyAll();
	}
	
	public synchronized void requestServed() {
		
		while(!this.arrived) {
			try {
				wait();
			}catch (InterruptedException e) {
				System.err.println(e);
			}
		}

		this.acceptingElevatorRequests = true;
				
		notifyAll();
	}
	

	public int getFloorNum() { return this.floorNum; }
	
	public int getDestFloor() { return this.destFloor; }
		
	public boolean hasArrived() {return this.arrived;}
	
	public synchronized  boolean hasRequest() {return this.bufferFull;}
	
	public String toString() {
		return "Making elevator request to: " + this.destFloor;
	}
}