/**
 * @author Billal Ghadie
 * @purpose          - A derivative of the Request class, the FloorRequest class 
 *                     stores all the information needed by the scheduler to handle
 *                     events generated by floors. 
 * @param direction  - The direction the calling customer would like to travel. 'u' for
 *       			   for and 'd' for down.
 */

public class FloorRequest extends Request{
	private String direction; 
	
	public FloorRequest(int n, String t, String d) {
		super(n, t);
		this.direction = d;
	}
		
	public String getDirection() { return this.direction; }
	
	public String toString() {
		return "Floor: " + this.getFloorNum() + " @ " + this.getTimeStamp() + " going: " + this.direction;
	}
	
}
